var myCards = [
    // { phrase:"fabricate",definition:"build; manufacture; invent"},
    // { phrase:"form",definition:"give shape to; establish"},
    // { phrase:"formulate",definition:"to put together add express"},
    // { phrase:"generate",definition:"produce; cause to be"},
    // { phrase:"identify",definition:"to show or to find"},
    // { phrase:"implement",definition:"to carry out; put into practice"},
    // { phrase:"install",definition:"place; put into position"},
    // { phrase:"inspect",definition:"examine carefully or officially"},
    // { phrase:"institute",definition:"set up; establish; begin"},
    // { phrase:"interpret",definition:"explain the meaning of"},
    // { phrase:"inquire",definition:"ask; make a search of"},
    // { phrase:"integrate",definition:"to add parts to make whole"},
    // { phrase:"investigate",definition:"search into; examine closely"},
    // { phrase:"judge",definition:"decide; form an estimate of"},
    // { phrase:"make",definition:"cause to come into being"},
    // { phrase:"maintain",definition:"to keep in an existing state; to continue in; carry on"},
    // { phrase:"manufacture",definition:"fabricate from raw materials"},
    // { phrase:"modify",definition:"to change; alter"},
    // { phrase:"monitor",definition:"to watch or observe"},
    // { phrase:"notice",definition:"comment upon; review"},
    // { phrase:"observe",definition:"inspect; watch"},
    // { phrase:"originate",definition:"initiate; to give rise to"},
    // { phrase:"organize",definition:"integrate; arrange in a coherent unit"},
    // { phrase:"perform",definition:"do; carry out; accomplish"},
    // { phrase:"plan",definition:"devise a scheme for doing; making; arranging activities to achieve objectives"},
    // { phrase:"probe",definition:"investigate thoroughly"},
    // { phrase:"produce",definition:"give birth or rise to"},
    // { phrase:"pursue",definition:"seek; obtain or accomplish"},
    // { phrase:"reason",definition:"think; influence another's actions"},
    // { phrase:"resolve",definition:"reduce by analysis; clear up"},
    // { phrase:"record",definition:"set down in writing or act of electronic reproduction of communications"},
    // { phrase:"recommend",definition:"advise; attract favor of"},
    // { phrase:"review",definition:"inspection; examination or evaluation"},
    // { phrase:"revise",definition:"to correct; improve"},
    // { phrase:"study",definition:"careful examination or analysis"},
    // { phrase:"seek",definition:"try to discover; make an attempt"},
    // { phrase:"search",definition:"examine to find something"},
    // { phrase:"scan",definition:"look through hastily; examine intently"},
    // { phrase:"screen",definition:"to separate; present; or shield"},
    // { phrase:"solve",definition:"find an answer"},
    // { phrase:"test",definition:"evaluate; examine"},
    // { phrase:"trace",definition:"to copy or find by searching"},
    // { phrase:"track",definition:"observe or plot the path of"},
    { phrase:"update",definition:"modernize; make current"}
];