module.exports = function(grunt) {
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    concat: {
      options: {
        separator: '\n',
        banner:   '/*! <%= pkg.name %> - v<%= pkg.version %> - ' +
          '<%= grunt.template.today("yyyy-mm-dd") %> */' + '\n'
      },
      dist_js: {
        src: [
          'js/**/*.js'
        ],
        dest: 'dist/FlashDeck.js',
      },
      dist_css: {
        src: [
          'css/**/*.css'
        ],
        dest: 'dist/FlashDeck.css',
      },
    },
    jshint: {
      files: [
        'dist/FlashDeck.js'
      ],
      options: {
        jshintrc: '.jshintrc'
      }
    },
    less : {
      options : {
        banner: '/* Auto generated by LESS compiler.  Do not modify!  */ \n'
      },
      src: {
        expand: true,
        cwd: './',
        src: [
          'css/**/*.less'
        ],
        dest: '../',
        ext: '.css'
      }
    },
    watch: {
      files:
      [
        'js/**/*.js'
      ],
      tasks:
      [
        'concat:dist_js',
        'jshint'
      ]
    }
  });

  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-contrib-less');
  grunt.loadNpmTasks('grunt-contrib-watch');

  // Default task(s) to run when we type c:\grunt.
  grunt.registerTask('default', [
    'concat',
    'jshint',
    'watch'
  ]);
};